project 'MasteringiOSFrameworks.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MasteringiOSFrameworks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'QMUIKit', '~> 4.0.0-beta'
  pod 'Masonry', '~> 1.1.0'
  # Pods for MasteringiOSFrameworks

  target 'MasteringiOSFrameworksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasteringiOSFrameworksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
